[project]
name = "user-invoice-db"
authors = [{name = "Erick-Allen"}]
version = "0.5.0"
dependencies = ["typer", "rich",]
[project.scripts]
userdb = "user_invoice_db.cli:app"
[project.optional-dependencies]
dev = ["pytest"]